### ISSUE TITLE
ArrayIndexOutOfBoundsException at OpenNlpEntityClassifier

### ISSUE THREAD

**Issue by ddebarbieux** [theopenconversationkit/tock-bot-open-data#2]
Hi,

You will find below a stack tace. I got it using tock bot open data.

bot_open_data_1    | INFO: {"queries":["Je cherche un train de Lille à Paris demain"],"namespace":"app","applicationName":"bot_open_data","context":{"language":"en","clientId":"ABwppHHMZ0a1rS_pJWI6PX8gu4855h6_T0znqwVxazqMlPIAlL0YFQMsY67yqY59UTZWBb2-0ztSAQ","dialogId":"5b87e1f291cebd0007bf0b5c","clientDevice":"ga","referenceDate":"2018-08-30T14:40:13.42489+02:00","referenceTimezone":"Europe/Paris","test":false,"registerQuery":true},"state":{"states":["search"]},"intentsSubset":[]}
bot_open_data_1    | Aug 30, 2018 12:40:13 PM okhttp3.internal.platform.Platform log
bot_open_data_1    | INFO: --> END POST (458-byte body)
nlp_api_1          | 2018-08-30T12:40:13.443 [vert.x-worker-thread-16] DEBUG fr.vsct.tock.nlp.front.storage.mongo.ClassifiedSentenceMongoDAO - { "applicationId" : "5b61bc4b8bc1bb0007618e1e", "language" : "en", "text" : "Je cherche un train de Lille à Paris demain", "status" : { "$in" : ["validated", "model"] } }
nlp_api_1          | 2018-08-30T12:40:13.445 [vert.x-worker-thread-16] DEBUG fr.vsct.tock.nlp.front.storage.mongo.ClassifiedSentenceMongoDAO - count : 0
nlp_api_1          | 2018-08-30T12:40:13.453 [vert.x-worker-thread-16] ERROR fr.vsct.tock.nlp.core.service.NlpCoreService - -1
nlp_api_1          | java.lang.ArrayIndexOutOfBoundsException: -1
nlp_api_1          | 	at fr.vsct.tock.nlp.opennlp.OpenNlpEntityClassifier.classify(OpenNlpEntityClassifier.kt:74)
nlp_api_1          | 	at fr.vsct.tock.nlp.opennlp.OpenNlpEntityClassifier.classify(OpenNlpEntityClassifier.kt:51)
nlp_api_1          | 	at fr.vsct.tock.nlp.opennlp.OpenNlpEntityClassifier.classifyEntities(OpenNlpEntityClassifier.kt:40)
nlp_api_1          | 	at fr.vsct.tock.nlp.model.service.NlpClassifierService.classifyEntities(NlpClassifierService.kt:102)
nlp_api_1          | 	at fr.vsct.tock.nlp.model.service.NlpClassifierService.classifyEntities(NlpClassifierService.kt:82)
nlp_api_1          | 	at fr.vsct.tock.nlp.core.service.NlpCoreService$parse$2.invoke(NlpCoreService.kt:69)
nlp_api_1          | 	at fr.vsct.tock.nlp.core.service.NlpCoreService$parse$2.invoke(NlpCoreService.kt:49)
nlp_api_1          | 	at fr.vsct.tock.nlp.core.service.NlpCoreService.classifyAndEvaluate(NlpCoreService.kt:152)
nlp_api_1          | 	at fr.vsct.tock.nlp.core.service.NlpCoreService.parse(NlpCoreService.kt:117)
nlp_api_1          | 	at fr.vsct.tock.nlp.core.service.NlpCoreService.parse(NlpCoreService.kt:64)
nlp_api_1          | 	at fr.vsct.tock.nlp.front.service.ParserService.parse(ParserService.kt:251)
nlp_api_1          | 	at fr.vsct.tock.nlp.front.service.ParserService.parse(ParserService.kt:142)
nlp_api_1          | 	at fr.vsct.tock.nlp.front.client.FrontClient.parse(FrontClient.kt)
nlp_api_1          | 	at fr.vsct.tock.nlp.api.NlpVerticle$configure$$inlined$blockingJsonPost$1.invoke(WebVerticle.kt:560)
nlp_api_1          | 	at fr.vsct.tock.nlp.api.NlpVerticle$configure$$inlined$blockingJsonPost$1.invoke(WebVerticle.kt:74)
nlp_api_1          | 	at fr.vsct.tock.shared.vertx.WebVerticle$executeBlocking$1.handle(WebVerticle.kt:484)
nlp_api_1          | 	at fr.vsct.tock.shared.vertx.WebVerticle$executeBlocking$1.handle(WebVerticle.kt:74)
nlp_api_1          | 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
nlp_api_1          | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
nlp_api_1          | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
nlp_api_1          | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
nlp_api_1          | 	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by vsct-jburet** [comment]
Indeed you found a bug - that I'm going to fix right now. 

But It's quite easy to workaround.

1) You use the "en" locale for a french sentence. Try to change the locale in the admin interface (right / top). This will fix the issue.

2) You can also try the stanford model, that is more heavily tested than the open nlp one (because we use usually stanford in production): Configuration ->  edit bot_open-data -> nlp engine -> update application

HTH
