### ISSUE TITLE
How to set credentials to the sncf api

### ISSUE THREAD

**Issue by ddebarbieux** [theopenconversationkit/tock-bot-open-data#3]
I fail to use tock bot open data due to 

```
<-- 401 UNAUTHORIZED https://api.sncf.com/v1/coverage/sncf/places?q=Lille (639ms)

(...)

bot_open_data_1    | 2018-08-30T13:09:08.860 [vert.x-worker-thread-14] INFO  fr.vsct.tock.bot.open.data.client.sncf.SncfOpenDataClient - {"message":"The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."}
```

I found in class SncfOpenDataClient, the following code
` .header("Authorization", Credentials.basic(OpenDataConfiguration.sncfApiUser, ""))`

What should I do when my password in not empty.

Thanks for your help.

**Comment by vsct-jburet** [comment]
from the README : 

> You will need a (free) SNCF Open Data key and to set the environment var (see OpenDataConfiguration).

So you need to set the java property "tock_bot_open_data_sncf_api_user" with your sncf key (look at the code https://github.com/voyages-sncf-technologies/tock-bot-open-data/blob/master/src/main/kotlin/fr/vsct/tock/bot/open/data/OpenDataConfiguration.kt#L29 )

HTH

**Comment by ddebarbieux** [comment]
Ok I set my username instead of my tocken.
