### ISSUE TITLE
FileNotFoundException when running test suite

### ISSUE THREAD

**Issue by ddebarbieux** [theopenconversationkit/tock-bot-open-data#4]
I got an error when running the test suite of bot open data:

`[ERROR] Caused by: java.io.FileNotFoundException: /home/xxxxxxxxxxx/git/tock-bot-open-data/target/test-classes/fr/vsct/tock/bot/open/data/story/GreetingsTest$greetings story displays welcome message with Messenger dedicated message WHEN context contains Messenger connector and fr locale$1.class (Nom de fichier trop long)`

I fix it by renaming the test "greetings story displays welcome message with Messenger dedicated message WHEN context contains Messenger connector and fr locale" with a shortest name.

Is-it an expected featuez of kotlin?

Thanks for your help?

**Comment by vsct-jburet** [comment]
Do not reproduce on my side ;). What is your OS/java version?

**Comment by ddebarbieux** [comment]
```
java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

```
cat /proc/version
Linux version 4.4.0-53-generic (buildd@lcy01-28) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
```

**Comment by vsct-jburet** [comment]
Do you use encrypted disk? see https://stackoverflow.com/questions/48338025/kotlin-on-linux-with-encrypted-home-java-io-filenotfoundexception-file-name-t
I'm going to commit an additionnal @DisplayName for the test

**Comment by ddebarbieux** [comment]
Yes I  use encrypted disk.
