### ISSUE TITLE
How to script the download of the app dump

### ISSUE THREAD

**Issue by ddebarbieux** [theopenconversationkit/tock-bot-open-data#6]
(1) I improved tock bot open data by adding new phrases in the NLP model. 
(2) Then I downloaded the app dump 
(3) Then I copied it into the resources
(4) Then I lauched the code from intellij.

I did the sequence many times, and I use to forgot steps (2) and (3). 

How to script them?

**Comment by vsct-jburet** [comment]
You can also use [gitter]( https://gitter.im/tockchat/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge) for this kind of question ;)

The new sentences are persisted in mongo. So if you use the docker mongo install, they should stay, even if you restart the stack.

We use the "bot_open-data.json" file to bootstrap new users. But in a dev team, we usually use a shared server. So we don't use scripting for this task.

If you need to script anyway, the best way is to use the admin rest services:

- get the list of current apps:
`curl http://localhost/rest/admin/applications -u admin@app.com:password`

- Then take the _id of an app and:
`curl http://localhost/rest/admin/application/dump/[the id] -u admin@app.com:password`
-> this is the bot_open-data.json

- to upload the file:
`curl -X POST http://localhost/rest/admin/dump/application -u admin@app.com:password -F ‘data=@path/to/local/file’`

HTH
